./mpc -acpt feature_test/feature1_block.pas test/f1.parse
./mpc -acpt feature_test/feature2_vardecl.pas test/f2.parse
./mpc -acpt feature_test/feature3_arraytype.pas test/f3.parse
./mpc -acpt feature_test/feature4_recordtype.pas test/f4.parse
./mpc -acpt feature_test/feature5_procfuncdecl.pas test/f5.parse
./mpc -acpt feature_test/feature6_compstmt.pas test/f6.parse
./mpc -acpt feature_test/feature7_ifstmt.pas test/f7.parse
./mpc -acpt feature_test/feature8_casestmt.pas test/f8.parse
./mpc -acpt feature_test/feature9_repeatstmt.pas test/f9.parse
./mpc -acpt feature_test/feature10_forstmt.pas test/f10.parse
